# Generated by Django 5.1.4 on 2025-01-04 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('details_id', models.AutoField(primary_key=True, serialize=False)),
                ('mo_name', models.CharField(max_length=255)),
                ('mo_bulding_no', models.CharField(max_length=255)),
                ('mo_area', models.CharField(max_length=255)),
                ('mo_city', models.CharField(max_length=255)),
                ('mo_pincode', models.IntegerField(unique=True)),
                ('mo_landmark', models.CharField(max_length=255)),
                ('mo_mobile', models.IntegerField(unique=True)),
                ('mo_email', models.EmailField(max_length=254, unique=True)),
                ('mo_food_license_no', models.CharField(max_length=255)),
                ('mo_food_serve', models.CharField(max_length=255)),
                ('mo_food_licence_photo', models.ImageField(blank=True, null=True, upload_to='food_licences/')),
                ('mess_images', models.ImageField(blank=True, null=True, upload_to='mess_images/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mess_app.user')),
            ],
        ),
    ]
